### ISSUE TITLE
Connecting to MAX! cube...

### ISSUE THREAD

**Issue by RavixModz** [mirko3000/MMM-max#1]
Hello,
I just tried to use the modul but the mirror always shows connecting to MAX! cube... . I used the correct ip. Do I have to active something on the dashboard of my router? (I'm using a Fritz box)

**Comment by RavixModz** [comment]
Im Terminal steht folgende Fehlermeldung:



> error: unable to resolve reference refs/remotes/origin/master: Invalid argument
> From https://github.com/MichMich/MagicMirror
>  ! [new branch]      master     -> origin/master  (unable to update local ref)
> error: unable to resolve reference refs/remotes/origin/MichMich-patch-1: Invalid argument
>  ! [new branch]      MichMich-patch-1 -> origin/MichMich-patch-1  (unable to update local ref)
> error: unable to resolve reference refs/tags/v2.1.1: Invalid argument
>  ! [new tag]         v2.1.1     -> v2.1.1  (unable to update local ref)
> 
> Unhandled rejection ReferenceError: i is not defined
>     at /home/pi/MagicMirror/modules/MMM-max/node_helper.js:30:18
>     at tryCatcher (/home/pi/MagicMirror/modules/MMM-max/maxcube/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/home/pi/MagicMirror/modules/MMM-max/maxcube/node_modules/bluebird/js/release/promise.js:512:31)
>     at Promise._settlePromise (/home/pi/MagicMirror/modules/MMM-max/maxcube/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._settlePromise0 (/home/pi/MagicMirror/modules/MMM-max/maxcube/node_modules/bluebird/js/release/promise.js:614:10)
>     at Promise._settlePromises (/home/pi/MagicMirror/modules/MMM-max/maxcube/node_modules/bluebird/js/release/promise.js:693:18)
>     at Async._drainQueue (/home/pi/MagicMirror/modules/MMM-max/maxcube/node_modules/bluebird/js/release/async.js:133:16)
>     at Async._drainQueues (/home/pi/MagicMirror/modules/MMM-max/maxcube/node_modules/bluebird/js/release/async.js:143:10)
>     at Immediate.Async.drainQueues (/home/pi/MagicMirror/modules/MMM-max/maxcube/node_modules/bluebird/js/release/async.js:17:14)
>     at runCallback (timers.js:574:20)
>     at tryOnImmediate (timers.js:554:5)
>     at processImmediate [as _immediateCallback] (timers.js:533:5)
> 
>

**Comment by mirko3000** [comment]
Hey, hast du das Submodule wie in der Anleitung steht initialisiert?

**Comment by RavixModz** [comment]
Ja, denke schon.
Werde es morgen nochmal versuchen.

**Comment by RavixModz** [comment]
Habe es nochmal versucht. Habe das Modul gelöscht und die Schritte nochmal durchgeführt. Ich erhalte jedoch noch immer die selbe Fehlermeldung im Terminal. Habe auch schon ohne erfolg versucht, den Spiegel allein mit dem MAX Modul zu starten, gleiche Fehlermeldung.
Kann es sein, dass ich ein nicht unterstütztes Modell habe? [URL=https://www.pic-upload.de/view-33017635/IMG_0799.jpg.html][IMG]https://www2.pic-upload.de/thumb/33017635/IMG_0799.jpg[/IMG][/URL]

**Comment by RavixModz** [comment]
https://www2.pic-upload.de/img/33017635/IMG_0799.jpg

**Comment by mirko3000** [comment]
Which version of MagicMirror are you using? I have tried with latest version, that works fine. I don't thinks it is an issue with the cube, if you keep it updated (MAX! firmware) there should be no problems. Only make sure you are not connected via the MAX! app or MaxBuddy.

**Comment by UMoshammer** [comment]
Got the same issue with a new fresh installation. 

Fixed it by changing the following in node_helper.js:

old:
`for (i = 0; i < devices.length; i++) {`
new:
`for (var i = 0; i < devices.length; i++) {`

The variable declaration was missing in the for-loop.

**Comment by mirko3000** [comment]
Thanks UMoshammer, fixed it and pushed to master.

**Comment by blazkom** [comment]
Hi, i have problem. I have install and add module to magic mirror but when mmm-max module is shown i only get header of module. I can never get temperatures of max modlues. I have enter correct IP

**Comment by mirko3000** [comment]
Hello @blazkom, please open a new issue for this.
Anyhow, please make sure you don't have any other client connected to the MAX gateway, else your magic mirror will not be able to connect. Can you send me your configuration?

**Comment by blazkom** [comment]
Hi,

there is my config file.

    {
module: 'MMM-max',
position: 'bottom_left',
header: '',  // This is optional
config: {
maxIP: "192.168.1.125",
twoColLayout: "true"
}
},

V V ned., 20. maj 2018 ob 18:11 je oseba mirko3000 <notifications@github.com>
napisala:

**Comment by mirko3000** [comment]
Hi @blazkom,
sorry for the late reply. Do you get any error in the logs? Can you try starting in debug mode (npm start dev) and checking the browser console (Developer mode)?
